### ISSUE TITLE
Consider changing some of your default keybindings

### ISSUE THREAD

**Issue by goldsborough** [zhuochun/md-writer#100]
Your keybindings for indenting lists and continuing lists on enter override the autocomplete feature in atom, which can be a quite painful an issue to track down because the atom-global keys for auto-completion (enter or tab) just wouldn't work on any markdown-files because of markdown-writer's bindings. I fixed it now by disabling all your keybindings and putting this in my keymap:

```cson
"atom-workspace atom-text-editor:not([mini])[data-grammar~='gfm']":
  "ctrl-enter": "markdown-writer:insert-new-line"
  "ctrl-tab"  : "markdown-writer:indent-list-line"
```

but I just wanted to suggest you also change those bindings. May confuse people updating the package then, but I think badness-by-default is not a good idea.

**Comment by zhuochun** [comment]
Duplicated of #98 . Will be fixed in next release.
