### ISSUE TITLE
octopress plugin {% highlight ruby %} confuses syntax-highlighting

### ISSUE THREAD

**Issue by efwe** [zhuochun/md-writer#104]
When i use the highlight plugin from octopress the formatting of the file somehow gets confused.
Right within the code-block the text-color turns violet and keeps like this to the end of the file.

Is this a 'bug' or missed I some configuration? I chose 'octopress' as the engine in the settings section.
![screen shot 2016-01-07 at 11 54 00](https://cloud.githubusercontent.com/assets/139730/12168903/9200249a-b535-11e5-9a61-4be75782fed3.png)

**Comment by efwe** [comment]
Oh. I saw, that the editor says 'GitHub Markdown' in the lower left corner. This could be a problem i think.

**Comment by zhuochun** [comment]
Markdown-Writer didn't handle any syntax highlighting.

This is a bug in Atom's Markdown language package. Refer to https://github.com/atom/language-gfm/issues/44 

Install https://github.com/burodepeper/language-markdown could solve this according to the comments.

**Comment by KaiBueker** [comment]
Thanks for the tip with https://github.com/burodepeper/language-markdown .
It solves the html underscore issue, fine.

**Comment by efwe** [comment]
Yes, thanks a lot. I also installed the other language package.
