### ISSUE TITLE
Featurerequest: shortcode for create link with target _blanc

### ISSUE THREAD

**Issue by KaiBueker** [zhuochun/md-writer#106]
Hey,

it is possible to create a link with target _blanc?

greetings
Kai

**Comment by zhuochun** [comment]
If you use Jekyll, kramdown could support `[link](url){:target="_blank"}`, standard markdown only supports HTML. `<a href="..." target="_blank">title</a>`.

We could add configuration for this.

**Comment by KaiBueker** [comment]
Thanks
currently I'm using Hugo (gohugo.io) with blackfriday markdown and no support for target="_blank".
It seems to me that i have to use the traditional way with html, perhaps with my own shortcode in atom.

**Comment by zhuochun** [comment]
Refer to https://github.com/zhuochun/md-writer/issues/104 , its not a bug in markdown-writer.

**Comment by zhuochun** [comment]
I have added link customization in latest 2.2.0.

You can add the following to your config, refer https://github.com/zhuochun/md-writer/wiki/Settings#project-specific-settings

``` cson
# inline link tag template
linkInlineTag: '<a href="{url}" target="_blank">{text}</a>'
# reference link tag template
referenceInlineTag: '<a href="{url}" title="{title}" target="_blank">{text}</a>'
referenceDefinitionTag: ''
```
