### ISSUE TITLE
Format Table does nothing

### ISSUE THREAD

**Issue by kjknudsen** [zhuochun/md-writer#110]
This maybe a documentation issue or a bug, I can't tell. If I select a table and execute "format table", nothing happens. Can you provide an example of how it's supposed to work?

**Comment by zhuochun** [comment]
What's your table content looks like?

**Comment by kjknudsen** [comment]
Here is what my table looks like.  When I selected the "Format Table" menu
item, nothing happens. I would have expected it to fix the alignment.

| col 1 | col 2 |
| :------ | :----- |
| Item One    | Item Two  |

**Comment by zhuochun** [comment]
Interesting. Will check this. Thanks.

**Comment by zhuochun** [comment]
Should be fixed in v2.3.0

**Comment by kjknudsen** [comment]
Perfect! Thank you.

**Comment by zhuochun** [comment]
Thanks for the feedback.

**Comment by SchillerQuinn** [comment]
A similar thing happened to me. My table however contained inline LaTeX which might be part of the problem. It works fine with tables with LaTeX in them.

```
| Week to miss | Utility |
|--------------|---------|
| Week 1| $U(u_2, u_3, u_4) = (0) +1/2 \left(1^1 5 +1^2 8 +1^3 13\right)= 13$ |
| **Week 2** | $U(u_1, u_3, u_4) = 3 +1/2 \left(1^1 (0) +1^2 8 +1^3 13\right) = 13.5$ |
| Week 3| $U(u_1, u_2, u_4) = 3 +1/2 \left(1^1 5 +1^2 (0) +1^3 13\right) = 12$ |
| Week 4| $U(u_1, u_2, u_3) = 3 +1/2 \left(1^1 5 +1^2 8 +1^3 13\right) =9.5$ |
```
