### ISSUE TITLE
Pressing Enter at the end of a list item doesn't continue list

### ISSUE THREAD

**Issue by tomatic** [zhuochun/md-writer#111]
It appears the most recent update (2.2.0) introduced a bug: When I'm writing an unordered list and press Enter at the end of a list item, instead of auto-prefixing the next line with a dash, I end up two lines down with a blank line between the last list item and my current position.

Example:

```
- List item

| <- cursor position after pressing Enter at the end of the item above
```

If I disable markdown-writer list-continuation works as expected:

```
- List item
- | <- cursor position
```

**Comment by zhuochun** [comment]
I can't reproduce the problem.

```
- List Item <enter here>
```
becomes
```
- List Item
- <cursor>
```
enter again (will remove the trailing empty list item)
```
- List Item

<cursor>
```

Can you list the packages installed and try with restart Atom?

**Comment by tomatic** [comment]
Restarting Atom apparently solved it. Sorry, should have tried that before submitting an issue...
