### ISSUE TITLE
keybinding configurations on Mac

### ISSUE THREAD

**Issue by Orebeer** [zhuochun/md-writer#113]
Unlike Windows, there is no config options within Atom's Mac app to manually override users' default keybinding settings with that of this package. Further, the keybindings for this package are also not listed within Mac users' Keybindings menus like those of other packages. 

As a great quick fix: it would be very helpful if you could please provide code documentation for users to manual insert all of your package's keybindings within our keymap files. 

Thanks in advance.

**Comment by zhuochun** [comment]
You should see it in Mac top bar, `Packages > Markdown Writer > Configurations > Create Default Keymaps` or `Command + shift + p` then enter `Markdown Writer Create Default Mapping`

Or copy and paste the mappings at https://github.com/zhuochun/md-writer/blob/master/keymaps/sample-osx.cson

**Comment by Orebeer** [comment]
Perfecto! Thanks for your timely help!
