### ISSUE TITLE
Adding fields to front matter?

### ISSUE THREAD

**Issue by sethxd** [zhuochun/md-writer#117]
I'm trying to add two fields to front matter generated when I use the command 'Markdown Writer: New Post'. I use `desc` for meta-description and also `tags`. My _mdwriter.cson file looks like this:

```
frontMatter: """
---
layout: "{layout}"
title: "{title}"
date: "{date}"
desc: "Insert description here"
tags: "insert tags here"
---
"""
```

Is this the right way to try to do this, and if so, what am I doing wrong?

**Comment by zhuochun** [comment]
Looks correct to me. What's the error?

**Comment by sethxd** [comment]
It's actually not throwing me an error, it just creates a new post with only the layout, title, and date front matter.

**Comment by sethxd** [comment]
My full config file is [here](https://github.com/sethxd/sethxd.github.io/blob/source/_mdwriter.cson), if that helps.

**Comment by zhuochun** [comment]
Can you try delete the line `siteLinkPath: path.join(atom.getConfigDirPath(), "#{@prefix}-links.cson")`?

**Comment by sethxd** [comment]
I just tried that and the `desc` and `tags` fields still don't show up in the front matter for a new post.

New to this so just want to make sure I'm not making a rookie mistake: I don't have to rebuild the package or anything once I set up the config file?

**Comment by zhuochun** [comment]
Don't have to rebuild the package. May have to restart Atom to load the config file because the config file is cached.

**Comment by sethxd** [comment]
It's totally working now! Thanks for your help & patience. Before, I tried totally closing out of Atom and re-opening, which didn't seem to work. This time, I opened dev tools and reloaded (CTRL + R on windows) and now it's working.

Thanks again for your help, and for making an awesome package.

**Comment by zhuochun** [comment]
Great. :+1:
