### ISSUE TITLE
Configure file path separator?

### ISSUE THREAD

**Issue by klassenjm** [zhuochun/md-writer#122]
I am using this package to work on markdown based documentation generated within Slate (https://github.com/tripit/slate).

I am using Atom on Windows.

It appears that in the context of Slate, that file paths must be expressed using a forward slash. The default for the Insert Image function (on Windows) is a backslash. This results in broken image rendering (at least for the context I am working in).

Would it be possible to configure the default file path separator somewhere within this package?

Thanks for the nice tool!

**Comment by zhuochun** [comment]
Good spot. Will fix and covert the path to forward slash, because these are url paths, which should be in forward slash.

**Comment by klassenjm** [comment]
Excellent. Thank you.

**Comment by zhuochun** [comment]
Fixed in `v2.3.2`
