### ISSUE TITLE
all lists not working

### ISSUE THREAD

**Issue by cdbattags** [zhuochun/md-writer#124]
I'm having issues with adding any kind of list (unordered and ordered). Can someone confirm that this is indeed a problem or am I just crazy? =P

Also, continuation of lists on enter is not working properly as well.

**Comment by ZelphirKaltstahl** [comment]
@cdbattags What kind of issues?

**Comment by zhuochun** [comment]
Please give examples, filenames of your files, reproducing steps. plus Atom version, plugin version. Thanks.

**Comment by zhuochun** [comment]
Closed because no enough info is provided. Feel free to attach more info to re-open this issue. Thanks.
