### ISSUE TITLE
insert link, search for blog posts

### ISSUE THREAD

**Issue by shawngraham** [zhuochun/md-writer#125]
Hi,

When I highlight a term and go to insert a link, the search for blogposts dialogue box does not appear; just the text to be displayed, web address, and title boxes. I've got atom 1.5.4, max os x yosemite. I look in the inspector, and see

```
<div style="display: none;"><label class="icon icon-search">Search Posts</label><atom-text-editor class="editor mini" tabindex="5" mini="" data-grammar="text plain null-grammar" data-encoding="utf8"></atom-text-editor><ul class="markdown-writer-list"></ul></div>
```

So I'm wondering if that display: none is the issue, and why that might be occurring...?

thanks

**Comment by zhuochun** [comment]
What's your config? Have you setup the posts URL in config? [Setup Guide](https://github.com/zhuochun/md-writer/wiki/Settings-for-Front-Matters)

**Comment by shawngraham** [comment]
I have now set up the posts, tags, categories URL in the config (and have used the scripts you provided there). Still no joy, but I'll keep tinkering. Thanks!

**Comment by zhuochun** [comment]
Do you mind share your configs? The global config and project specific config (if you created).

**Comment by shawngraham** [comment]
Hi,
No problem. The config files:
https://github.com/smgprojects/notebook/blob/master/_config.yml

https://github.com/smgprojects/notebook/blob/master/_mdwriter.cson

...thanks; much appreciated.

**Comment by shawngraham** [comment]
ah! I'm a doughhead. I studied this: https://github.com/zhuochun/zhuochun.github.io/blob/cb34e3c16d42c52b281c34920ad55bbca223ac23/_mdwriter.cson and realized what I was doing wrong. All works now, thanks!
