### ISSUE TITLE
How to customize the behaviour of this package from within one's config.cson file?

### ISSUE THREAD

**Issue by fusion809** [zhuochun/md-writer#127]
Hi,

I personally prefer single asterisks (`*`) to italicize text in markdown, as opposed to the underscores (`_`) used by this package. I was wondering how I might get this behaviour by modifying my `~/.atom/config.cson` file. I know how to get this desired behaviour by forking this package (e.g., see [this fork](https://github.com/fusion809/md-writer) of mine, in which I've done this), but forks can be tricky to keep up-to-date due to conflicting files. I have also asked this question at [discuss.atom.io](https://discuss.atom.io/t/how-do-i-change-the-default-characters-used-to-italicize-text-by-the-markdown-writer-package/27041) if relevant; asking at both places in case one provides me with a better or faster answer than the other. 

Thanks for your time,
Brenton

**Comment by zhuochun** [comment]
You can manually edit your atom's `config.cson`, there should be a `markdown-writer` key, in the key, overwrite any fields you wanted.

The list of over-writable fields listed in https://github.com/zhuochun/md-writer/blob/master/lib/config.cson

Or you can create project specific config, there is a command `Markdown Write: Create Project Configs`.

**Comment by fusion809** [comment]
Where does this `markdown-writer` key go? Under `core`, `extra`, or somewhere else? This is my `config.cson`: 

```cson
"*":
  core:
    allowPendingPaneItems: false
  editor:
    invisibles: {}
  "exception-reporting":
    customFileTypes:
      ".yml$": "toggle-soft-wrap"
    userId: "20e33b17-b6ee-be85-6d79-5468d2ceffbc"
  "rss-ticker":
    feed: "https://aur.archlinux.org/rss/"
    fileTypes:
      emacs: "source.lisp"
      spacemacs: "source.lisp"
  welcome:
    showOnStartup: false
".basic.html.text":
  editor:
    softWrap: true
".source.yaml":
  editor:
    softWrap: true
```

like I am thinking of adding something like:

```cson
editor:
  textStyles:
    italic:
      before: "*", after: "*"
```

to it.

**Comment by zhuochun** [comment]
Should be:

``` coffee
"*":
  "markdown-writer":
    textStyles:
      italic:
        before: "*", after: "*"
```

**Comment by fusion809** [comment]
Thanks, it worked!
