### ISSUE TITLE
Config for automatic lists

### ISSUE THREAD

**Issue by puranjayjain** [zhuochun/md-writer#134]
@zhuochun I was wondering if, there can be a configuration setting (boolean) to enable a mode:

- In which when the user presses enter (in a line with bullet points or any other form of list) the cursor goes to the next line 
- automatically inserting the bullet point (and incrementing if necessary e.g. 1. then 2.)

I'll be happy to start a PR on your green light :smile:

**Comment by zhuochun** [comment]
Hi, these features are already supported and enabled in Markdown filetype in the package.

**Comment by zhuochun** [comment]
There are some other features wanted listed as enhancement in the issues list if you are interested.

**Comment by puranjayjain** [comment]
@zhuochun thanks for pointing out. yes i'll start some PRs for these features right away :grinning:

**Comment by zhuochun** [comment]
I will re-organized the issues a bit and categorize the enhancement tag more clearly.

I think #126 and #109 are the top wanted features so far. #126 looks like to be easier to support. #109 is similar to insert link.
