### ISSUE TITLE
"Copy Image to Site Image Directory" copies the files in the root of a Project folder

### ISSUE THREAD

**Issue by benediktwinder** [zhuochun/md-writer#139]
Is it possible to copy the inserted Images in the current folder? Lets say you have following folder structure:

Folder A
-- File.md
Folder B
-- File2.md
-- File3.md
Folder C
-- File4.md

If you insert a picture in File.md the images folder will not be created inside the folder "Folder A". The image folder will be created in the root of the project folder. Maybe somone have an idea. Thanks a lot.

**Comment by zhuochun** [comment]
You can try by set `siteImagesDir: "{directory}"` in your config

**Comment by benediktwinder** [comment]
Thank you very much. I've searched for variables but can't find anything. But about this variable i don't think. Thanks a lot!

**Comment by zhuochun** [comment]
Not working for you? I tried with settings below and worked for me.

```
  "markdown-writer":
    siteDraftsDir: "_drafts/{year}/"
    siteLinkPath: "~/github/markdown-writer/sample/links.cson"
    siteLocalDir: "~/github/zhuochun.github.io"
    siteImagesDir: "{directory}"
```

**Comment by benediktwinder** [comment]
Sorry for my bad english. It's working perfectly. :+1:  Thank you!

**Comment by zhuochun** [comment]
Great. Thanks.
