### ISSUE TITLE
After updating on June 7 to version 2.3.4, continue list on new line is not working

### ISSUE THREAD

**Issue by lmcneel** [zhuochun/md-writer#140]
Directly after updating, pressing enter in a markdown document was placing 2 blank lines on each return when in a list.

I restarted Atom and now enter only returns to the next line (expected behavior); however, it still does not continue the  list as it did before the update.

I am running Atom version 1.8.0 and Markdown-Writer Version 2.3.4.

I did not see any errors in the dev console window to post.

**Comment by zhuochun** [comment]
I cannot re-produce this problem with the same Atom + Markdown-Writer version.

When you restarted, were you tested in a Markdown file?

**Comment by lmcneel** [comment]
Yes - the extension is .md. The issue is still occurring in the editor today.

Is there a setting that needs to be configured for the new list item on enter to work?

I am going to try to uninstall markdown-writer and reinstall it. Maybe something went wrong with the update.

**Comment by lmcneel** [comment]
Reinstalling Markdown-Writer did not fix the issue.

**Comment by lmcneel** [comment]
I have found the issue. Thank you for looking into this - in the global settings, somehow under the option "Packages With Keymaps Disabled" markdown-writer was listed.

I removed the package name from that setting and the package is now working. 

Thank you again - I really like your package.

**Comment by zhuochun** [comment]
Thanks for the investigation 👍
