### ISSUE TITLE
Feature Request: New shortcut keys for inserting html elements

### ISSUE THREAD

**Issue by brabulla** [zhuochun/md-writer#142]
Hi,

I just started using both this plugin and markdown, and while formatting a markdown document, I felt like adding some extra customization through indenting, or breaking lines. I found that by default there are not many options for this through markdown, but then I found that they are doable, by using raw html. 

This is quite bothersome, to write "\<br>" tags and "\&nbsp;"s, so I thought a great addition to this plugin would be to support insertion of these characters through shortcuts, perhaps something like cmd-shift-space for the non breaking space, and cmd-shift-enter for the br?

THanks for your time, and for the great plugin,
Brabulla.

**Comment by zhuochun** [comment]
Maybe try custom snippets provided by Atom?

**Comment by zhuochun** [comment]
Can use emmet plugin for more HTML completions as well. Thanks.
