### ISSUE TITLE
How to block keyblindings applying on the sentence before?

### ISSUE THREAD

**Issue by Quantizen** [zhuochun/md-writer#143]
For example, when I typed the sentence 

```
example sentence
```

and then if I type `cmd + '`, it will become

```
'example sentence'.
```

But what I want is 

```
example sentence``
```

how to make this possible?

**Comment by zhuochun** [comment]
enter a space, then `cmd + '`. when you inside/around a word, the action is applied to the word.

**Comment by Quantizen** [comment]
Thanks for your reply. But when I write in Chinese,
```
例，子
```
and then `cmd+'` will make it into
```
`例，子`
```
while what I want is 
```
例，`子`
```

**Comment by zhuochun** [comment]
can select the `子` then `cmd+'`, will quote only the selection.

a word is defined by Atom's internal API (if I am not wrong, a word is separated by space/enter), so it might not take care of the `，` correctly.

**Comment by zhuochun** [comment]
You can't. You have to enter a space then `cmd+'`

**Comment by Quantizen** [comment]
okay， I understand.

**Comment by zhuochun** [comment]
👍

**Comment by zhuochun** [comment]
Ok. I understood what you mean now.

You want to have a setting to disable the auto styling to nearest word in Chinese. If disabled, the style will just add to the end of sentence.

Current behaviour:

```
a word_ --> a **word_**
```

Disable auto-styling, it will become:

```
a word_ --> a word**_**
```
