### ISSUE TITLE
`markdown-writer:open-cheat-sheet` :does not work

### ISSUE THREAD

**Issue by pkjkrai66** [zhuochun/md-writer#144]
`markdown-writer:open-cheat-sheet` is not working in my case. But I can open it from "C:\Users\TZ\\.atom\packages\markdown-writer\CHEATSHEET.md"

**Comment by zhuochun** [comment]
Do you see any error messages? and try it with restart Atom?

**Comment by pkjkrai66** [comment]
It does not open when preview of some other markdown file is already open, else it works.
![md writer](https://cloud.githubusercontent.com/assets/19630517/16551639/38cd4404-41d8-11e6-8829-23110f6f7bd9.jpg)

**Comment by zhuochun** [comment]
Ok I found the `\` in Windows file path is escaped to `%5C`, so the file path passed to markdown-preview is not correct in Windows.
