### ISSUE TITLE
How to add additional grammars?

### ISSUE THREAD

**Issue by zhengpd** [zhuochun/md-writer#145]
I'm using [nvatom](https://atom.io/packages/nvatom) and its grammar scope is `source.gfm.nvatom`, which isn't included in Markdown Writer's grammars list right now. Is there any way to configure Markdown Writer to support `source.gfm.nvatom`?

**Comment by zhuochun** [comment]
Edit your global config, find `markdown-writer` (if not exists, please add it), add:

``` json
"markdown-writer":
    "grammars": [
        'source.gfm'
        'source.gfm.nvatom'
        'source.litcoffee'
        'text.md'
        'text.plain'
        'text.plain.null-grammar'
    ]
```

Feel free to submit a PR to add it to Markdown Writer as well. 💃

**Comment by zhuochun** [comment]
The line is at https://github.com/zhuochun/md-writer/blob/master/lib/config.coffee#L22

**Comment by zhengpd** [comment]
Thanks for your reply. A PR is created and I'm closing this issue.
