### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by cokelly** [zhuochun/md-writer#15]
I receive the following warning for md-writer on Atom (0.174.0) on Arch Linux:

```
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

Atom.Object.defineProperty.get (/home/USERAtom/share/atom/resources/app/src/atom.js:55:11)
Object.registerHelper (/home/USER/packages/markdown-writer/lib/main.coffee:83:9)
```

**Comment by zhuochun** [comment]
Since the last update of the plugin, Atom APIs has changed a lot.

I have started to revise the code and fix broken APIs. But it will take a while due my time limit. Thanks.

**Comment by cokelly** [comment]
No problem. I wish I had the technical chops to help out.

**Comment by zhuochun** [comment]
I have updated the package and have fixed any deprecated APIs I found. Please update and let me know everything is ok for you. Thanks.

**Comment by cokelly** [comment]
Hi. Thanks for this. Might be just me but I'm still picking up a 'deprecated selectors' flag for keymaps/md.cson:

```
Use the 'atom-text-editor' tag instead of the 'editor' class. 
```

**Comment by zhuochun** [comment]
Could you update again or re-install (backup your configs first)? I have renamed the keymaps file. So `keymaps/md.cson` shouldn't exists anymore.
