### ISSUE TITLE
Support insert image from clipboard

### ISSUE THREAD

**Issue by zhuochun** [zhuochun/md-writer#159]
At insert image dialog, if there is picture in clipboard, fill the src with special `@clipboard`

After confirmed insert, write clipboard image to local directory and insert the path (similar to copy to local directory)

**Comment by zhuochun** [comment]
Refer to https://github.com/sagaraya/image-copipe

**Comment by pabloab** [comment]
The [markdown-img-paste](https://atom.io/packages/markdown-img-paste) package already let you paste an image from clipboard directly to markdown, with some cloud  alternatives. Would be really great to have this on md-writer. BTW this feature exist here on Github comments and on Stackexchange posts, is extremely useful.

**Comment by zhuochun** [comment]
Supported in `v2.7.1` release
