### ISSUE TITLE
Convert selection of new line separated values into a list

### ISSUE THREAD

**Issue by Wamadahama** [zhuochun/md-writer#163]
I think this would be great productivity.

Sample Input
```md
foo 
bar
bazz
```

After selecting and running command (Key sequence / Command Palette)
It will be converted to 
```md 
- foo 
- bar
- bazz
```

and perhaps extend it to also insert ```[ ]``` task items

**Sample Input**
```md
foo 
bar
bazz
```
**Output:**
```md 
- [ ] foo 
- [ ] bar
- [ ] bazz
```

Edit:

I haven't looked at the source but it think it should just be simple

i.e 
```
split the section by \n
prepend - or - [ ]
```

Great plugin by the way.

**Comment by zhuochun** [comment]
I believe this is supported already. Try command `Markdown Writer Toggle OL/UL/Task`.

Follow https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps if you want to have key mappings.

**Comment by Wamadahama** [comment]
Sorry I missed that, my bad.
