### ISSUE TITLE
I want to edit the template for post but I don't kown which file to modify

### ISSUE THREAD

**Issue by webkong** [zhuochun/md-writer#173]
<img width="319" alt="mkw" src="https://cloud.githubusercontent.com/assets/10398591/18384996/696f08d2-76c0-11e6-95a3-3e0bcca2a8c6.png">

**Comment by webkong** [comment]
who can help me ?  很急很关键。

**Comment by zhuochun** [comment]
https://github.com/zhuochun/md-writer/wiki/Settings-for-individual-projects no need to edit source code

**Comment by webkong** [comment]
Thank you so much , I configured it successfully.  💯 :)

**Comment by zhuochun** [comment]
Great 👍
