### ISSUE TITLE
Ctrl+b does not trigger bold

### ISSUE THREAD

**Issue by orschiro** [zhuochun/md-writer#175]
Dear @zhuochun,

Thank you so much for your package!

I enabled md-writer for `txt` files and tried `Ctrl+b` to toggle a selected text bold but all it does is presenting me with the menu shown in the screenshot. 

Do you have any advice for me?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18522715/6cfcbeaa-7ab1-11e6-9650-6cb23e508a1e.png)

![image](https://cloud.githubusercontent.com/assets/170947/18522718/7401365e-7ab1-11e6-82df-7266f05f1481.png)

**Comment by zhuochun** [comment]
Did you add the default keymaps? Refer to https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps

> From version 1.5.0, default keymaps that come with this package are removed (except enter/tab).
> You can execute command `Markdown Writer: Create Default Keymaps` to append the original list of keymaps to your keymap config file, then modify them based on your needs.

**Comment by orschiro** [comment]
Problem solved. 

Thank you @zhuochun! 

:-)

-Robert

**Comment by zhuochun** [comment]
Great thanks.
