### ISSUE TITLE
Ambiguous meaning of "cmd-h"

### ISSUE THREAD

**Issue by MuscleRumble** [zhuochun/md-writer#18]
I don't know if `cmd-h` (or the letter `h` in general) is somehow a convention for strikethrough, but I'd like to keep the `cmd-h` shortcut to "Hide Application". I've tried to customize my keymap to unset `cmd-h`, but I'm not sure how to do it correctly.

**Comment by zhuochun** [comment]
Go to `Atom` -> `Open your Keymap`, then you can add the following to disable `cmd-h`.

```
".platform-darwin .editor:not(.mini)":
    "cmd-h": "unset!"
```

**Comment by MuscleRumble** [comment]
Perfect! That works! :) I tried it without `:not(.mini)`, but didn't know what it means (or still don't know xD). Thanks!!

**Comment by zhuochun** [comment]
For the latest markdown-writer (`0.10.1`), the selector has changed due to API updates:

```
".platform-darwin atom-text-editor":
    "cmd-h": "unset!"
```
