### ISSUE TITLE
Keep text highlighted during formating and actually make a toggle

### ISSUE THREAD

**Issue by bombledmonk** [zhuochun/md-writer#182]
Currently, if text is selected and a shortcut is applied to that word the `**imABoldWord**` gets applied, but the cursor ends up after the word with the text no longer selected.  This introduces two issues.  One cannot toggle the bold text off easily, and one cannot then add a different emphasis to the word easily.

It would be nice if the styling actions could keep the entire word and applied styling in a selection so one can toggle or add other styling.  
So instead of this after ctrl+b: 
![image](https://cloud.githubusercontent.com/assets/4141691/19602552/3bff4eb0-9773-11e6-9b6a-7c148af128e2.png)
I would get this
![image](https://cloud.githubusercontent.com/assets/4141691/19602525/267efdb0-9773-11e6-9878-7585b9947b92.png)
That way if I were to hit ctrl+b on the word again it would remove the styling to look like this.
![image](https://cloud.githubusercontent.com/assets/4141691/19602605/6e489854-9773-11e6-8470-1fcc79f67c07.png)

I know this might be a bit of a preference, but I think it's more intuitive that the way it works now.

**Comment by zhuochun** [comment]
Thanks for the suggestion. Will look into this.
