### ISSUE TITLE
Object.extname is deprecated.

### ISSUE THREAD

**Issue by zhuochun** [zhuochun/md-writer#184]
Argument to `path.extname` must be a string
```
Object.extname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:20:10)
Object.getEditor (/Users/zhuochun/github/markdown-writer/lib/helpers/template-helper.coffee:99:30)
InsertImageView.display (/Users/zhuochun/github/markdown-writer/lib/views/insert-image-view.coffee:190:41)
atom-text-editor.<anonymous> (/Users/zhuochun/github/markdown-writer/lib/markdown-writer.coffee:115:37)
CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
```

**Comment by zhuochun** [comment]
Fixed in https://github.com/zhuochun/md-writer/commit/05e7438470d1ef83747e72ff53f41575af45a6c0

**Comment by pauljacobson** [comment]
This just came up for me in Atom. Will it be fixed in an update soon?

**Comment by zhuochun** [comment]
@pauljacobson this issue was fixed and released 7 mths ago. If it reappeared, I need more info, e.g. provide atom version, installed package version, error traces.

**Comment by mrbbp** [comment]
`
Argument to path.extname must be a string

Object.extname - /Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:20:10
Object.getEditor - /Users/xxx/.atom/packages/markdown-writer/lib/helpers/template-helper.coffee:99:30
InsertImageFileView.display - /Users/xxx.atom/packages/markdown-writer/lib/views/insert-image-file-view.coffee:192:41
InsertImage.trigger - /Users/xxx/.atom/packages/markdown-writer/lib/commands/insert-image.coffee:17:21
HTMLElement.<anonymous> - /Users/xxx/.atom/packages/markdown-writer/lib/markdown-writer.coffee:157:37
CommandRegistry.handleCommandEvent - <embedded>:11:349290`

Atom 1.45.0 x64 osx 10.14.6
Electron 4.2.7
Chrome 69.0.3497.128
Node: 10.11.0
