### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by ceciliassis** [zhuochun/md-writer#185]
Every time I hit a simple shortcut like crtl+b nothing happens, then I need to go to the end of the word and this happens:  **do****** 

This after the UPDATE.

**Comment by zhuochun** [comment]
Can check your keymaps were set correctly? https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps

**Comment by ceciliassis** [comment]
Hey, I've found the problem. My keymaps were doubled. Issue closed!
