### ISSUE TITLE
Append </ br> to last line on Shift+Enter

### ISSUE THREAD

**Issue by juschu** [zhuochun/md-writer#187]
Markdown should be intuitive. But at least in vanilla Markdown a single new line means not a new line in the parsed document. You could press enter twice, but then you get a new paragraph. Perhaps you just wanted a new line. 
Perhaps you could choose a markdown parser that inserts </ br> also on a single new line, but perhaps you're in a situation where you can't choose the parser or you just want to write vanilla Markdown so you can be sure it works with every markdown parser. And as far as I know every Markdown parser would take any HTML and insert it in the parsed document.

**Comment by zhuochun** [comment]
I was using snippets to do the similar, not sure would it be useful for you.

```
  'Line Break Dot':
    'prefix': '.'
    'body': "<br/>\n"
  'Line Break Dot2':
    'prefix': '..'
    'body': ".<br/>\n"

  'Line Break Comma':
    'prefix': ','
    'body': "<br/>\n"
  'Line Break Comma2':
    'prefix': ',,'
    'body': ",<br/>\n"
```
