### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by yoimbert** [zhuochun/md-writer#19]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.registerCommand (/Users/Yohann/.atom/packages/markdown-writer/lib/main.coffee:74:9)
```

**Comment by zhuochun** [comment]
I am working on this. Hopefully I will be able clear the last bit of deprecated stuffs and publish the newer version by this weekend. Thanks.

Closed as a duplicated of #15
