### ISSUE TITLE
Support Image Resize at "insert image dialog"

### ISSUE THREAD

**Issue by DerekTso** [zhuochun/md-writer#191]
sometimes, the original image is too large, it'd better to resize it within the insert image window.

**Comment by zhuochun** [comment]
Is it similar to https://github.com/zhuochun/md-writer/issues/30 or perform image resize based on the height/width entered?

**Comment by DerekTso** [comment]
oh yes, is it available already?

**Comment by zhuochun** [comment]
Merge under https://github.com/zhuochun/md-writer/issues/30
