### ISSUE TITLE
Moving the markdown 'markup' and 'table' menu selections to the atom menu bar

### ISSUE THREAD

**Issue by 9ASHIPU4Q0V** [zhuochun/md-writer#192]
Love the markdown writer package. 

Constantly forget the syntax of formatting. Now must dive down three menu layers to see this (<Packages><Markdown Writer><Markup> or <Table>).  

Is there a way to elevate these two menus to be on the main atom menu bar? Then it would be one step away!

**Comment by zhuochun** [comment]
Might try out package https://atom.io/packages/tool-bar-markdown-writer or use command `Cmd  + p`, then type the style name.
