### ISSUE TITLE
can't use the short-cut key stroke

### ISSUE THREAD

**Issue by IamAlchemist** [zhuochun/md-writer#197]
`shift-cmd-i` doesn't work in atom 1.15.0, after installation of md-writer 2.6.4.

in markdown writer settings, `keybindings` only show two keybinding 'enter' and 'tab'...
![screen shot 2017-03-20 at 10 35 34](https://cloud.githubusercontent.com/assets/6259666/24087409/9893d5f4-0d59-11e7-962d-d532e260f0bf.png)

**Comment by zhuochun** [comment]
> Please execute command `Markdown Writer: Create Default keymaps` to append the original list of keymaps to your keymap config file, then modify them based on your needs. Refer to [wiki][31ebd53f].

  [31ebd53f]: https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps "Settings for Keymaps"
