### ISSUE TITLE
Table of content

### ISSUE THREAD

**Issue by albuic** [zhuochun/md-writer#201]
A command to generate a Table of content would be great.
An "update on save" checkbox in the settings could be available too.

**Comment by black-snow** [comment]
+1000 - other available TOC plugins do not work (anymore) with atom 1.32.1

**Comment by zhuochun** [comment]
**Table of contents (TOC)** (`markdown-writer:insert-toc`), and support following options (global or inline):
  - `depthFrom`, `depthTo`: range of headings to be displayed.
  - `insertAnchor`: insert TOC with anchor link.
