### ISSUE TITLE
Export to html?

### ISSUE THREAD

**Issue by dahead** [zhuochun/md-writer#203]
Hi guys,

first of all, thanks to the developer for the great plugin.
Maybe I am to stupid, but i can't find a way to publish (or convert) my markdown "post" to a html post. 
I can get the html source into the clipboard via `ctrl+shift markdown copy html` but i don't find a way to create the html file automatically.

Thanks for your help!

**Comment by zhuochun** [comment]
Hi, you can try out https://atom.io/packages/markdown-preview-plus which supports HTML export and a better alternative to default markdown-preview package.

**Comment by dahead** [comment]
Thank you!
