### ISSUE TITLE
issue with yaml-loader parsing

### ISSUE THREAD

**Issue by aje4u2i** [zhuochun/md-writer#204]
This is my yaml file contents:
---
myfile:
  - you: have to
    put: a newline character as the last line of this file

while parsing with yaml-loader it shows:
ERROR in ./~/json-loader!./~/yaml-loader!./src/layouts/file.yaml
Module build failed: YAMLException: end of the stream or a document separator is expected at line 2, column 10:
        "myfile": [

**Comment by zhuochun** [comment]
@aje4u2i afaik, Markdown-Writer do not work on YAML file. The commands won't trigger in non-markdown files.
