### ISSUE TITLE
Ignore Kramdown settings

### ISSUE THREAD

**Issue by Stinobe** [zhuochun/md-writer#205]
I was wondering if it's possible to ignore Kramdown settings, for example when you have a link and set the target to `_blank` it's like everything that follows is according to the editor italic.

``` markdown
Lorem ipsum dolor sit amet, [consectetur](http://lipsum.com/){:target="_blank"}  adipiscing elit.
```

**Comment by zhuochun** [comment]
This should be because of Atom's language-gfm syntax highlight package. E.g. https://github.com/atom/language-gfm/issues/146
