### ISSUE TITLE
Hugo support

### ISSUE THREAD

**Issue by insuusvenerati** [zhuochun/md-writer#206]
Any chance for Hugo support?

**Comment by zhuochun** [comment]
I am not familiar with Hugo. By default, any markdown files are supported.

Defaults configs for an engine are defined at https://github.com/zhuochun/md-writer/blob/v2.6.5/lib/config.coffee#L36 Feel free to add some for Hugo.

Configs that can be overwritten are listed at https://github.com/zhuochun/md-writer/blob/v2.6.5/lib/config.cson

**Comment by jhabdas** [comment]
Hugo supports front-matter in JSON, YAML and TOML. So it seems using YAML for parity with Jekyll would be best to add support without complicating things initially. Note on the config override Hugo doesn't have the concept of a `siteDraftsDir: "_drafts/"` as it's [fast enough not to need](https://forestry.io/blog/hugo-vs-jekyll-benchmark/) to exclude files in many circumstances.

**Comment by jhabdas** [comment]
Hugo supports front-matter in JSON, YAML and TOML. So it seems using YAML for parity with Jekyll might be best to add support without complicating things initially.

Note on the config override Hugo doesn't have the concept of a `siteDraftsDir: "_drafts/"` as it's [fast enough not to need](https://forestry.io/blog/hugo-vs-jekyll-benchmark/) to exclude files in many circumstances.

**Comment by jhabdas** [comment]
Hugo supports front-matter in JSON, YAML and TOML. So it seems using YAML for parity with Jekyll might be best to add support without complicating things initially.

Note on the config override Hugo doesn't have the concept of a `siteDraftsDir: "_drafts/"` as it's [fast enough not to need](https://forestry.io/blog/hugo-vs-jekyll-benchmark/) to exclude files in many circumstances.

@zhuochun if it makes any difference to you Netlify is moving or has moved Smashing Magazine from WordPress to Hugo—Jekyll couldn't scale for the occasion.

**Comment by zhuochun** [comment]
I think stick YAML would be the best.

`siteDraftsDir` is optional config, it can be set to empty or posts directory.

I believe most of features are compatible with Hugo. What is missing is putting Hugo default conventions as an engine config.
