### ISSUE TITLE
Provide proper highlighting in editor

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [zhuochun/md-writer#207]
Compare how the same markdown looks in sublime markdown gfm and atom md-writer:

Sublime Markdown GFM:
![image](https://user-images.githubusercontent.com/6263572/27158093-f6c10ef2-515c-11e7-98aa-486bcd36f07a.png)

Atom:
![image](https://user-images.githubusercontent.com/6263572/27158078-e357985e-515c-11e7-8182-4314a76423c0.png)

In atom highlighting is only shown in the final generated document. So you can't get a feel of the document's structure when you're editing it. 

Yes I know I can generate the preview with a hotkey but nothing will provide faster feedback than having highlighting in the editor. That boosts the productivity quite a lot.

Please consider this feature request for future releases.

Thanks

**Comment by zhuochun** [comment]
Syntax highlighting is not part of this package. In Atom, bold/italic etc styling are handled by color scheme, e.g. https://atom.io/themes/pen-paper-coffee-syntax
