### ISSUE TITLE
Increase number when using markup for ordered list

### ISSUE THREAD

**Issue by Morikko** [zhuochun/md-writer#209]
Now, when you use the markup to create an ordered list, they all start with the number one.
 
My text:
![image](https://user-images.githubusercontent.com/7831572/27989449-9ce56cd4-63fe-11e7-8ce4-f3fbf107bae1.png)

I select:
![image](https://user-images.githubusercontent.com/7831572/27989464-090d66f0-63ff-11e7-8381-e6360ab499a6.png)

After the markup:
![image](https://user-images.githubusercontent.com/7831572/27989452-a9b66dfa-63fe-11e7-8a33-080770897cb6.png)

What I find more logical:
![image](https://user-images.githubusercontent.com/7831572/27989453-afbd057e-63fe-11e7-9c0b-9392c088e672.png)

I would find interesting to increase the number if the lines are following each other without a blank line.

**Comment by zhuochun** [comment]
The current workaround is to run an additional command `Correct Order List Orders`

**Comment by zhuochun** [comment]
Resolved in `v2.7.0`
