### ISSUE TITLE
[Feature request] Header folding

### ISSUE THREAD

**Issue by werunom** [zhuochun/md-writer#218]
Hi! I request you to include the header folding functionality. 

Currently, there is a [package](https://atom.io/packages/markdown-folding) available for doing this. Given that, I still think this feature needs to be implemented in md-writer package for the following reasons - 

1. since md-writer package attempts to be a comprehensive package for markdown writing, including the folding feature makes sense. This will obviate installing extra packages.

2. markdown-folder package has not been updated in a long time. That package was like a quick fix to an earlier discontinued package. After this fix, the package has not been developed further. 

3. Moreover, markdown-folder package does the bare minimum work and therefore, lacks a few features that a _folder_ should have. For instance, there is no incremental unfolding (that is, if I try to unfold H1 header, only H2 headers should be visible; instead of that, at present all sublevel headers are all unfolded). 

Given all these, please consider including this feature. Thanks!

**Comment by zhuochun** [comment]
I have never used folding before, might take a look when I have time.

**Comment by werunom** [comment]
Nice! Folding comes very handy. For instance, in my academic writing (in markdown with pandoc conversion), the document becomes really long and folding of all the sections except few help in focusing. 
PS - the [markdown-editing package](https://packagecontrol.io/packages/MarkdownEditing) of sublime includes folding option.

**Comment by tymokvo** [comment]
I think this is related, so I didn't want to open an issue...but it would be nice if it were possible to fold the url of a link when writing so that it would go from:

`[Google](http://www.google.com)` to `[Google](...)` or something so that links are not so distracting while writing.

**Comment by nocibambi** [comment]
Yes, this is a thing I also miss from Atom.

Here are two packages, which implement it separately though:
* [markdown folding](https://atom.io/packages/markdown-folding)
* [markdown fold](https://atom.io/packages/markdown-fold)

An there is a related [issue](https://github.com/atom/atom/issues/11838) as well.

**Comment by zhuochun** [comment]
Added new command `markdown-writer:fold-links` to fold inline links, released in `v2.8.0`.

**Comment by zhuochun** [comment]
Some folding functions are available now in `v2.11.0`.

**Comment by werunom** [comment]
Nice! Thanks for implementing.

**Comment by lzkelley** [comment]
@zhuochun would it be possible to add the little, clickable arrows for folding instead of setting up a shortcut key or command palette?

**Comment by zhuochun** [comment]
@lzkelley Atom seems do not expose API to add the clickable arrows. So no obvious way to add them.

**Comment by lzkelley** [comment]
@zhuochun I don't know any of the internal workings,  but I think the package [custom-folds](https://github.com/bsegraves/custom-folds) does it
