### ISSUE TITLE
imageTag: inserts base url

### ISSUE THREAD

**Issue by srxqds** [zhuochun/md-writer#220]
I want make imageTag as imageTag: 

`![{alt}](\{\{site.baseurl\}\}/{src})`

the "{{site.url}}" as constant insert into markdown file.
eg: I want
 

`[test]({{site.baseurl}}/images/2017/09/test.png)`

but the result is,

`[test]({{site.baseurl}}/../../images/2017/09/test.png)`

how can I do it by correct config!

thank you

**Comment by zhuochun** [comment]
Hard code `site.baseurl` in template. Or add

```
# Template variables is a key-value map used in template string
templateVariables:
  siteBaseUrl: "..."
```

change imageTag to `{siteBaseUrl}/{src}`

**Comment by srxqds** [comment]
I change to below:
templateVariables:
  siteBaseUrl: "{site.baseurl}"

imageTag: "![{alt}]({siteBaseUrl}/{src})"

It is also not work, should siteBaseUrl be specific site?

And I have another question: how to change the markdown file font size. The default size is too little?

**Comment by zhuochun** [comment]
You cannot reference to `{site.baseurl}`, must put in the actual URL in `siteBaseUrl`.

Change font use Atom editor font.

**Comment by srxqds** [comment]
But I modify `siteBaseUrl` with actual URL:
`siteBaseUrl: https://srxqds.github.io
imageTag: "![{alt}]({siteBaseUrl}/{src})`

It is also not work correct:
![test](https://srxqds.github.io//../../images/2017/09/test.png)`

may you help me?

**Comment by zhuochun** [comment]
try `![{alt}]({siteBaseUrl}/{relativeSiteSrc}` :thinking:

**Comment by srxqds** [comment]
It is ok now, Thank you !!!!

**Comment by zhuochun** [comment]
Great 🎉
