### ISSUE TITLE
critic-markup

### ISSUE THREAD

**Issue by olafklingt** [zhuochun/md-writer#221]
are you interested to add critic markup to this package? I looked at your code and it looked to me that it would be easier to be added to your package than to write a new one.

**Comment by zhuochun** [comment]
Hi, feel free to submit a pull request. I am not so familiar with Critic Markup, could refer to https://github.com/zhuochun/md-writer/tree/master/lib/filetypes on adding new filetype support.

**Comment by olafklingt** [comment]
You can find information about it here: http://criticmarkup.com/

Especially here http://criticmarkup.com/users-guide.php

It is not so much a different file type rather than something to be used in combination with Markdown. 
I am interested in two things insertion and removal of the markup tags. And a go to next markup tag.

I can work on it slowly.
