### ISSUE TITLE
return key disabled

### ISSUE THREAD

**Issue by Steve-O-Cassels** [zhuochun/md-writer#224]
Steps to reproduce:

Open atom with markdown-writer enabled.
Edit any file, saved, unsaved.
Also cccurs when new file (no file suffix)

Behaviour : return key does **not** do return action

return key works when markdown-writer is disabled

Ubuntu
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.3
├── autocomplete-css@0.17.3
├── autocomplete-html@0.8.1
├── autocomplete-plus@2.35.11
├── autocomplete-snippets@1.11.1
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.41.1
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.5
├── exception-reporting@0.41.4
├── find-and-replace@0.212.2
├── fuzzy-finder@1.5.9
├── github@0.6.2
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.62.3
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.15
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.251.10
├── snippets@1.1.5
├── spell-check@0.72.2
├── status-bar@1.8.13
├── styleguide@0.49.7
├── symbols-view@0.118.0
├── tabs@0.107.2
├── timecop@0.36.0
├── tree-view@0.217.9
├── update-package-dependencies@0.12.0
├── welcome@0.36.5
├── whitespace@0.37.3
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.0
├── language-csharp@0.14.2
├── language-css@0.42.5
├── language-gfm@0.90.1
├── language-git@0.19.1
├── language-go@0.44.2
├── language-html@0.47.7
├── language-hyperlink@0.16.2
├── language-java@0.27.4
├── language-javascript@0.127.3
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.42.0
├── language-property-list@0.9.1
├── language-python@0.45.4
├── language-ruby@0.71.3
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.3
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.2
├── language-toml@0.18.1
├── language-typescript@0.2.1
├── language-xml@0.35.2
└── language-yaml@0.30.2

Community Packages (34) /home/developer/.atom/packages
├── atom-beautify@0.30.5
├── atom-elixir@0.2.3
├── autocomplete-ctags@0.4.1
├── autocomplete-elixir@1.5.16
├── autocomplete-modules@1.7.3
├── busy-signal@1.4.3
├── change-case@0.6.5
├── color-picker@2.2.5
├── custom-title@1.0.1
├── file-icons@2.1.13
├── git-plus@7.10.0
├── git-time-machine@1.5.9
├── highlight-selected@0.13.1
├── intentions@1.1.5
├── language-docker@1.1.8
├── language-elixir@0.20.3
├── language-gherkin@1.0.4
├── language-lua@0.9.11
├── language-nginx@0.8.0
├── linter@2.2.0
├── linter-elixir-credo@1.1.0
├── linter-eslint@8.4.0
├── linter-lua@1.0.4
├── linter-luacheck@2.0.1
├── linter-stylelint@4.0.2
├── linter-ui-default
├── markdown-toc@0.4.2
├── markdown-writer (disabled)
├── minimap@4.29.7 (disabled)
├── multi-cursor@2.1.5
├── open-on-github@1.2.1
├── prettier-atom
├── react@0.16.2
└── split-diff@1.5.1

**Comment by zhuochun** [comment]
Did you customised any config? There is a `grammars` [config](https://github.com/zhuochun/md-writer/blob/master/lib/config.coffee#L21), that if you have set it for markdown, it could cause misbehave.

Another way is go to plugin and disable the keybindings.

**Comment by Steve-O-Cassels** [comment]
Thanks @zhuochun - I was also having the issue getting to the settings due to the Atom bug.

No, I've no customised config.

Once settings were up, I was able to disable the keybindings.

**Comment by zhuochun** [comment]
Are you able to reproduce this in the newer Atom version and/or reinstall package?
