### ISSUE TITLE
Change links to be like footnotes

### ISSUE THREAD

**Issue by kescobo** [zhuochun/md-writer#225]
Wondering if it would be possible to have the option of doing footnote-like links. In other words, something like:

```md
Here's some text and [a link][1].

Other content.

[1]: http://example.com
```

rather than

```md
Here's some text and [a link](http://example.com).

Other content.
```

I personally find the former syntax much more readable in the text editor. Based on the way footnotes work now, it should be as easy as changing the logic so that if some text is highlighted, it puts brackets around it and avoid the `^`. In other words, right now if I highlight text and add a footnote, it becomes:

```
highlighted text[^1]

[^1]: http://example.com
```

but it should be

```
[highlighted text][1]

[1]: http://example.com
```

**Comment by zhuochun** [comment]
Put `-` in title field to create an empty title reference link.
