### ISSUE TITLE
Bug in coloring of the markdown in the editor.

### ISSUE THREAD

**Issue by zeeshansayyed** [zhuochun/md-writer#226]
When you write a math formula between the dollar signs, it gets colored green in the editor. But if you use this formula in your markdown ($*$), all the remaining text is also colored green. The following sample markdown should reproduce the error.

# This is a test

```markdown
- Ideally, only the math between the dollar signs should be colored gree. Like this formula $a=b+c$.
- If you notice, this sentence is not green. Everything is fine so far.
- Let's put in the formula which causes the bug $*$. This is it.
- Everything from the previous formula which is just an asterisk is still green including this line.
```

**Comment by zhuochun** [comment]
Syntax highlighting is not provided by this plugin. Can check https://github.com/atom/language-gfm/ the official package
