### ISSUE TITLE
shortcuts don't work on ubuntu

### ISSUE THREAD

**Issue by uocxp** [zhuochun/md-writer#228]
Is there any way to get the "md-writer" shortcuts work on ubuntu? because there's no cmd key on Linux.

**Comment by kylebarron** [comment]
[This page](https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps#add-your-keymaps) in this repository gives the default keymaps for macOS. To make them work for linux, add them to your `keymap.cson` and just change `.platform-darwin` to `.platform-linux` and `cmd` to `ctrl`. This is what my `keymap.cson` looks like:
```cson
".platform-linux atom-text-editor[data-grammar='source md']":
  "shift-ctrl-K":  "markdown-writer:insert-link"
  "shift-ctrl-I":  "markdown-writer:insert-image"
  "ctrl-v":        "markdown-writer:insert-image-clipboard"
  "ctrl-i":        "markdown-writer:toggle-italic-text"
  "ctrl-b":        "markdown-writer:toggle-bold-text"
  "ctrl-'":        "markdown-writer:toggle-code-text"
  "ctrl-k":        "markdown-writer:toggle-keystroke-text"
  "ctrl-h":        "markdown-writer:toggle-strikethrough-text"
  "ctrl-alt-1":    "markdown-writer:toggle-h1"
  "ctrl-alt-2":    "markdown-writer:toggle-h2"
  "ctrl-alt-3":    "markdown-writer:toggle-h3"
  "ctrl-alt-4":    "markdown-writer:toggle-h4"
  "ctrl-alt-5":    "markdown-writer:toggle-h5"
  "shift-ctrl-O":  "markdown-writer:toggle-ol"
  "shift-ctrl-U":  "markdown-writer:toggle-ul"
  "shift-ctrl->":  "markdown-writer:toggle-blockquote"
  'shift-ctrl-"':  "markdown-writer:toggle-codeblock-text"
  "ctrl-j ctrl-p": "markdown-writer:jump-to-previous-heading"
  "ctrl-j ctrl-n": "markdown-writer:jump-to-next-heading"
  "ctrl-j ctrl-d": "markdown-writer:jump-to-reference-definition"
  "ctrl-j ctrl-t": "markdown-writer:jump-to-next-table-cell"
```
(the `atom-text-editor[data-grammar='source md']` means that the shortcuts won't function outside of a markdown document.

**Comment by chewenkai** [comment]
According to the instruction of the [wiki document](https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps).
:

> To add the original default keymaps, run command (`cmd + shift + p`), enter `Markdown Writer: Create Default Keymaps`


The generated `keymap.cscon` of mine works on Linux machine:

> ".platform-linux atom-text-editor:not([mini])":
>   "shift-ctrl-K": "markdown-writer:insert-link"
>   "shift-ctrl-I": "markdown-writer:insert-image"
>   "ctrl-i":       "markdown-writer:toggle-italic-text"
>   "ctrl-b":       "markdown-writer:toggle-bold-text"
>   "ctrl-'":       "markdown-writer:toggle-code-text"
>   "ctrl-h":       "markdown-writer:toggle-strikethrough-text"
>   "ctrl-1":       "markdown-writer:toggle-h1"
>   "ctrl-2":       "markdown-writer:toggle-h2"
>   "ctrl-3":       "markdown-writer:toggle-h3"
>   "ctrl-4":       "markdown-writer:toggle-h4"
>   "ctrl-5":       "markdown-writer:toggle-h5"

**Comment by zhuochun** [comment]
Try restart Atom, and/or remove `.platform-linux`.
