### ISSUE TITLE
Using one word sentences generates garbage text after return.

### ISSUE THREAD

**Issue by PROF-FART** [zhuochun/md-writer#229]
Something in Markdown-writer is creating weird acronyms from two or more one-word sentences.

I first noticed it when I typed "Old. Retro." followed by a full paragraph of text. After I hit return, Atom inserted "OLE." (with period) on the new line.

"That. Big. Sofa." gets "THAU." on the new line. "Dont. Worry. About. It." gets "DONU." Besides the first letters matching the first word, I can't figure out any rhyme or reason to the inserted text. If I type just "Hey." and then return, I get nothing. "Hey. Stop." gets me "HEZ."

It's taking everything except the last letter of the first word and then inserting the next alphabetical letter from the last letter. Then a period. 

I fixed it by turning off Markdown-writer's keybindings.

**Comment by zhuochun** [comment]
Oops, will fix this. The single word is recognised as an alphabet ordered list, E.g.

```
a. item a
b. item b
```
