### ISSUE TITLE
How to set image size?

### ISSUE THREAD

**Issue by rickhg12hs** [zhuochun/md-writer#247]
I've tried several different markdown methods to change the image size but none seem to actually work.  What is the correct recipe for setting an image size?

**Comment by rickhg12hs** [comment]
Ah, found it.

From `man 7 markdown` on my system ...

> Images
>      Admittedly, it's fairly difficult to devise a "natural" syntax for placing images into a plain text document format.
> 
>      Markdown uses an image syntax that is intended to resemble the syntax for links, allowing for two styles: inline and reference.
> 
>      Inline image syntax looks like this:
> 
>                ![Alt text](/path/to/img.jpg)
> 
>                ![Alt text](/path/to/img.jpg =Optional size "Optional title")
> 
>      That is:
> 
>      ·   An exclamation mark: `!`;
> 
>      ·   followed by a set of square brackets, containing the `alt` attribute text for the image;
> 
>      ·   followed by a set of parentheses, containing the URL or path to the image, an optional `size` attribute (in width c height
>          format) prefixed with a `=`, and an optional `title` attribute enclosed in double or single quotes.
> 
>      Reference-style image syntax looks like this:
> 
>                ![Alt text][id]
> 
>      Where "id" is the name of a defined image reference. Image references are defined using syntax identical to link references:
> 
>                [id]: url/to/image  =Optional size "Optional title attribute"
>

**Comment by rickhg12hs** [comment]
... although, the "Optional title" from the previous comment above doesn't seem to work.

**Comment by zhuochun** [comment]
Afaik markdown doesn't support image size by default.

If the markdown parser you used supports it, you can [config setting](https://github.com/zhuochun/md-writer/wiki/Settings) `imageTag: "![{alt}]({src})"` to `imageTag: "![{alt}]({src} ={width} {height})".

**Comment by rickhg12hs** [comment]
@zhuochun So why does `Packages -> Markdown Writer -> Markup -> Insert Image` have a popup with `width`, `height`, and `alignment`?

**Comment by mrbbp** [comment]
is ther a way to calcule in the image Tag, like that?
`imageTag: ![{alt}]({src}){width={width/2}px height={height/2}px}"`

**Comment by zhuochun** [comment]
math like `{width/2}` is not supported, you have to adjust in the insert image view as of now

**Comment by mrbbp** [comment]
sad!
