### ISSUE TITLE
Upload image - problem 

### ISSUE THREAD

**Issue by mett96** [zhuochun/md-writer#248]
when I try to upload an image, the written code is wrong. 

The main issue is that the root contain the main folder which contains the markdown file. 
I try to explain better.

My markdown file is contained in the folder1. 
In the folder1 there is folder2 that contains the image. 
|---folder1
    |---- project.md
    |----folder2
         |------image

When I upload the image, the root is 
/folder1/folder2/image
In this way the image isn't uploaded. 
Instead the root should be /folder2/image

**Comment by zhuochun** [comment]
Couldn't get your question, especially on the upload part because the package doesn't provide any upload functionality.

**Comment by mett96** [comment]
With upload image I mean the possibility to insert an image into the markdown code. The function’s name in Atom is insert Image

**Comment by zhuochun** [comment]
You can modify `imageTag` config, change `src` to other possible variances, probably `relativeSiteSrc`.

```
imageTag: "![{alt}]({src})"
```

Variances:

- `src`: default
- `relativeFileSrc`: relative image path respect to markdown file
- `relativeSiteSrc`: relative image path respect to root directory of project

**Comment by mett96** [comment]
Perfect, 
Thank you I will change this setting
