### ISSUE TITLE
Insert images

### ISSUE THREAD

**Issue by Lloyar** [zhuochun/md-writer#252]
When I use Ctrl + Shift + I insert images ，I get `![test](images/2018/10/test.png)` insert my .md document rather than `![test](/images/2018/10/test.png)`. 
Kramdown engine not display the image because loss the "/".

Could you advise?
Thanks :)

**Comment by zhuochun** [comment]
Can change config add `/` or try change `src` -> `relativeSiteSrc`.

···
# Image tag template
imageTag: "![{alt}](/{src})"
···

**Comment by Lloyar** [comment]
> Can change config add `/` or try change `src` -> `relativeSiteSrc`.
> 
> ```
> # Image tag template
> imageTag: "![{alt}](/{src})"
> ```

Thank you so much!
