### ISSUE TITLE
Toggle blockquote option duplicates the selected text when selecting paragraphs

### ISSUE THREAD

**Issue by pauljacobson** [zhuochun/md-writer#257]
### Describe the bug

I noticed that when I select paragraphs of text in a Markdown document, and then format it as blockquote text, some of the text in the selected text is duplicated when the text is formatted as blockquote text.

### To Reproduce

1. I selected text in a Markdown file in Atom.
2. I used the command palette to **Toggle blockquote**
3. Running this seems to duplicate parts of the selected text, particularly when the text is in paragraphs

### Expected behavior

Using the **Toggle blockquote** option should just add `>` to the beginnings of the lines of the selected text, not alter the text itself.

### Screenshots

Here is a demonstration of the issue. When I selected single lines to format as blockquotes, it worked as expected. However, watch what happens when I do the test using a paragraph of text with multiple sentences:

![atom_markdown_blockquote_rendering](https://user-images.githubusercontent.com/2912202/47283279-53842480-d5eb-11e8-951d-2662fadec360.gif)

### Additional context

This issue only started in the last few days.

Atom version 1.31.2
Markdown Writer version 2.10.1
macOS 10.14

**Comment by zhuochun** [comment]
Looks like a similar issue as #222 , but in a different place. Will take a look.
