### ISSUE TITLE
Pasting image from clipboard saves in wrong directory with multiple projects

### ISSUE THREAD

**Issue by kylebarron** [zhuochun/md-writer#265]
**Describe the bug**
When there are multiple projects open, pasting an image from the clipboard saves the image in the _first_ project and not necessarily the project within which the current file is.

**To Reproduce**

```bash
mkdir project-one project-two
touch project-two/markdown.md
atom project-one
atom project-two --add
```
Then open `project-two/markdown.md` in Atom and paste an image from clipboard. It saves to `project-one/img/...`.

**Expected behavior**
The image should save to a directory within the currently-active project.

**Comment by zhuochun** [comment]
Thanks for the report. Fix will be released in next release shortly.
