### ISSUE TITLE
Support WikiLinks (CamelCase) 

### ISSUE THREAD

**Issue by SemanticBeeng** [zhuochun/md-writer#270]
**Problem** 
Need to maintain extensive wikis of concepts and hard to get into the "flow" if I have to maintain the links manually.

**Solution**
Implement support for WikiLink syntax like in `SoyWiki` http://danielchoi.com/software/soywiki.html (below is taken from "CamelCase WikiLinks rule!")

 * Besides being the original, CamelCase is the most elegantly minimalist approach to linking wiki pages together -- "with no additional markup whatsoever," as Ward Cunningham put it.
 * It encourages you more than other wiki link patterns to create wiki pages with succinctly descriptive names that are easy to remember.
 * Because the link pattern is so minimal and succinct, writing wiki links interrupts your flow of thought less than other wiki link patterns.
 * CamelCase wiki links are less noisy than other link patterns in raw plain text form. This also contributes to flow.
 * The CamelCase link pattern is very conducive to storing wiki pages in plain text files: the page names can map directly to Unix file names without any awkward character escaping or munging.

Must be able to refactor while auto maintaining all usages (see "Wiki refactoring" section in link above).

**Describe alternatives you've considered**
Have done extensive research and tried all I could. Using Confluence for years but it is quite heavy and does not support `markdown`.

**Comment by zhuochun** [comment]
This looks like an interesting. Providing wiki-like management is a much wider topic.

I used this plugin for managing notes. I do find linking among notes are the most troublesome. I'd prefer to treat wiki handling as code, and use https://langserver.org/ to provide wiki features. In this case, I wouldn’t put the features in this package.

**Comment by zhuochun** [comment]
With the more popular `[[link]]` started in recent years. I'd think it is a better alternative and there are specific tools that better support it (obsidian/logseq).
