### ISSUE TITLE
EACCES, permission denied '/github'

### ISSUE THREAD

**Issue by changjiashuai** [zhuochun/md-writer#28]
new post permission denied '/github'

**Comment by zhuochun** [comment]
Please configure your post directory in settings -> https://github.com/zhuochun/md-writer#setup

**Comment by stefania11** [comment]
I have the same issue and I don't understand these instructions
"For Jekyll/Octopress users, you can add these scripts to your Jekyll directory and upload the generated JSON files.""

My website only runs on GH pages and not sure in this case where and if the files would be generated. 

Would be very helpful if you could provide screenshots and more details if possible

**Comment by zhuochun** [comment]
@stefania11 If you did not use Jekyll for GH pages. You don't have to setup this. If you do use Jekyll, just download or create the three files [download here](https://gist.github.com/zhuochun/fe127356bcf8c07ae1fb), put in your repo, commit and upload. Then put the links to these files in settings.

**Comment by zhuochun** [comment]
Hi, I have revised the README docs. Hope it would be clearer.
