### ISSUE TITLE
Slash (/) in ToC

### ISSUE THREAD

**Issue by mjaquiery** [zhuochun/md-writer#281]
**ToC links containing / character are broken**
When using Insert/Update Table of Contents the links created do not work where there is a / in the heading name. This is because the ToC truncates / to an empty string, while the code responsible for assigning ids to headings replaces / with -. 

**To Reproduce**
1. produce a document with a / in the headings:
```
## Test/Example
```
2. insert ToC
3. Open in browser and click the link.
4. Note that the search path in the URL does not match the header tag's id.

**Expected behavior**
The link should scroll the page to the appropriate header.

**Comment by zhuochun** [comment]
Which tool does you use to generate from Markdown to HTML?

Currently, the TOC follows GitHub markdown rendering, `/` is removed when generating anchor ID.

**Comment by mjaquiery** [comment]
I think it’s this: https://atom.io/packages/markdown-to-html
If it’s the fault of the interpreter then sorry for bothering you!
Matt

**Comment by zhuochun** [comment]
Cross checked on https://stackedit.io/app , slash is removed in anchor generation.

Thanks for the report.
