### ISSUE TITLE
TOC automatic transcoding of Chinese into random code

### ISSUE THREAD

**Issue by somno1ency** [zhuochun/md-writer#283]
When I write md in Chinese and generate TOC, the link of anchor will be translation to random code. Although I know it's automatic translation, but can I display it in Chinese by configuring it to be untranslated?

**Comment by zhuochun** [comment]
The random code is escaped characters, which could be used by directly using it actually.

It requires to replace the URL generator library I used.

**Comment by somno1ency** [comment]
ok, I see,thank you.

**Comment by zhuochun** [comment]
Reopen the issue because I do want to fix the escape characters.
