### ISSUE TITLE
Subfolder Title as FrontMatter Category

### ISSUE THREAD

**Issue by wimmstr** [zhuochun/md-writer#294]
**Is your feature request related to a problem? Please describe.**
I organize my .md files into categories, which each have their own subfolder in /_posts. Octopress used the subfolder name to populate the "categories:" field in Frontmatter. 
Using "{dir}" in the frontmatter template does not work.

**Describe the solution you'd like**
Populate the "Categories:" field in the files frontmatter with the name of its subfolder. E.g.: /_posts/example becomes "Categories: example" upon file creation.

**Describe alternatives you've considered**
Only alternative Ive come up with is putting an empty "categories:" field in the frontmatter and fill it by hand.

**Comment by zhuochun** [comment]
Interesting. I have not thought about this before.

I have some questions to understand more:

- Do you use `New Post` command in this case? How are you using it?
- If the subfolders have multiple levels, e.g. `_posts/cat1/cat2/cat3`, what is the behavior of it?

**Comment by zhuochun** [comment]
https://github.com/zhuochun/md-writer/wiki/Settings#support-hugo-academic-theme-structure

Can give a try with `{category}` in file name
