### ISSUE TITLE
[Feature request] Autocomplete unordered lists within ordered lists

### ISSUE THREAD

**Issue by bwhrsc** [zhuochun/md-writer#299]
Sometimes I like to create an old

1. First thing
    * Unordered comment
    * Another unordered comment
2. Second thing

It would be lovely for markdown-writer to allow autocomplete in these cases.

**Comment by bwhrsc** [comment]
To clarify, I'm talking about the ability to (explicitly or implicitly) declare the sublist format.

So in the example above, hitting enter after item 2. would give a 3. at list level 0, and then indenting would give a *.

**Comment by zhuochun** [comment]
Can give a try by using `{category}`

https://github.com/zhuochun/md-writer/wiki/Settings#support-hugo-academic-theme-structure
