### ISSUE TITLE
Can you support vscode?

### ISSUE THREAD

**Issue by liuzhihangs** [zhuochun/md-writer#300]
**Is your feature request related to a problem? Please describe.**

Recently, I found that Atom has been stuck for a long time, and I want to switch to vscode, but this plugin is indeed very good.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhuochun** [comment]
VSCode has [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one). Can give it a try.
