### ISSUE TITLE
Add support for Hugo "Academic Theme" directory structure: /title-of-post/index.md

### ISSUE THREAD

**Issue by sebastientaggart** [zhuochun/md-writer#301]
**Is your feature request related to a problem? Please describe.**

The Hugo [Academic Theme](https://github.com/gcushen/hugo-academic) uses a fairly non-standard directory structure:

```
/posts/
  /This-is-My-Cool-post/
    /assets/
      embedded-picture.jpg
    index.md
    featured.jpg
  /This-is-Another-Post/
    /assets/
      neat-picture.jpg
      other-file.doc
    index.md
```

With the Markdown Writer configuration, I see that I can set a custom target directory for new posts:

![image](https://user-images.githubusercontent.com/4606476/81205469-be603b00-8f98-11ea-9d38-9359dfac9e35.png)

However, after trying `{slug}`, `{title}`, etc. I can't find a way to make the directory equal to the title of the post.

I can force the "New Post File Name" to be `index.md` as the directory structure above demands:

![image](https://user-images.githubusercontent.com/4606476/81205604-f10a3380-8f98-11ea-98a7-dda47ab6dba8.png)

**Describe the solution you'd like**

I would like the ability to use `{slug}` in the "Site Posts Directory" configuration option, such that when I create a new post with:

![image](https://user-images.githubusercontent.com/4606476/81206041-81487880-8f99-11ea-8362-97bfe4f0560c.png)

**Describe alternatives you've considered**

Another approach might be to do this with a bash script, and not rely on Markdown Writer at all to create new posts.  Unfortunately this would mean losing some of the great functionality with the Front Matter configuration.  Also this breaks up the workflow with two tools instead of one... doing this just with Markdown Writer in the Atom GUI would be much easier.

Just in case it's helpful, I went ahead and wrote a bash script to do this:

```new.sh
#!/bin/bash

# Simple bash file to create a new post per Hugo Academic's expected directory
# structure.  https://github.com/gcushen/hugo-academic is a theme for Hugo, a
# static site generator.  The expected structure for new posts is (relative to
# the root of the project):
#
# /posts/Long-Title-Name-of-Post/index.md <- the actual post
# /posts/Long-Title-Name-of-Post/assets/ <- directory where images, etc. go
#
# This script attempts to sanitize the user input, leaving behind alphanumeric
# characters and dashes.

## Usage
#
#  ./new "The Cool Title of My New Post"
#
# This script created the directory relative to its location.  I run it from /content/ because
# I want /content/posts/Cool-New-Post/index.md to be created.

# Make sure user supplies a title
if [ -z "$1" ]; then
  echo 'You must supply a post title, e.g.'
  echo '  ./new "The Cool Title of My New Post"'
  exit 1
fi

# Sanitize the input
SANIN=${1// /-} # replace spaces with dashes
SANIN=${SANIN//_/-} # replace underscores with dashes
SANIN=${SANIN//[^a-zA-Z0-9\-]/} # remove everything except alphanumeric or dash

# Before we create directories and files, double check they don't exist
if [[ ! -e "./posts/${SANIN}/" ]]; then
  mkdir -p "./posts/${SANIN}/assets/"
  touch "./posts/${SANIN}/index.md"
else
  echo "The directory /posts/${SANIN}/ already exists!  Aborting."
  exit 1
fi
```

I have also searched for other similar requests here:

- https://github.com/zhuochun/md-writer/issues/206 "Hugo Support", but this does not apply to this request as Hugo does not natively use the directory structure above.
- https://github.com/zhuochun/md-writer/issues/294 "Subfolder Title as FrontMatter Category" is similar, and, if implemented could sort of be used to accomplish the use case described here (albeit not as conveniently, depending).

**Additional context**

I realize that I mentioned "Hugo Academic Theme" at the start of this ticket, but in fact this request isn't specific to that particular theme.  I think this kind of flexibility with creating posts would benefit everyone, especially those who prefer having a directory for each post (or logical grouping of content related to a specific markdown file).

**Comment by zhuochun** [comment]
You can try this configuration:

```
sitePostsDir: "posts/"
newPostFileName: "{slug}/index.md"
siteImagesDir: "{directory}/assets/"
```
