### ISSUE TITLE
Creating link with reference at the end

### ISSUE THREAD

**Issue by Trudko** [zhuochun/md-writer#35]
Hi :)

first of all thanks for the plugin. You done a ton of work!

Right now new link is created in format (Link Text)[link address]. Were you think about implementing it by using (link text)[1]

[1]: link address?

I am asking because I am writing blog post in Atom which I paste to Wordpress. I have plugin for markdown to html but it seems it doesn't support first link form.

**Comment by zhuochun** [comment]
When you insert link, put `-` in the title box. A reference link will inserted.
