### ISSUE TITLE
Optionally copy image to local images folder

### ISSUE THREAD

**Issue by funkypenguin** [zhuochun/md-writer#37]
Hey man,

Thanks for making atom.io a better markdown editor :) I've been trying use the "insert image" feature to insert an image - it works as described for a remote image, but I can't see how to optionally copy it to a local folder. Could you advise?

Thanks :)
:smile:

**Comment by zhuochun** [comment]
Copy image only works for images on your computer, like images in other directories.

I did not test copying images from remote/online. When a URL is inserted, the copy option will not show up.

**Comment by zhuochun** [comment]
Copy image from online is not supported.
