### ISSUE TITLE
pressing tab while in a list should indent the list

### ISSUE THREAD

**Issue by PeterDeKeer** [zhuochun/md-writer#38]
Hi,

While editing a ordered or unordered list, if i press TAB directly after "* " or "2. ", should indent the list.
Not adding the TAB

Thx.

**Comment by zhuochun** [comment]
Is this a common behavior in markdown editors?

**Comment by tobikris** [comment]
It definitely is and is really useful. I noticed that the "outdenting" works as expected (when pressing Shift+Tab). Would be awesome if you added the behavior as described.

**Comment by tobikris** [comment]
Works as expected for me, thanks!

**Comment by zhuochun** [comment]
@tobikris great! :+1: thanks for letting me know!
