### ISSUE TITLE
Highlighting header marked with ======

### ISSUE THREAD

**Issue by yantongl** [zhuochun/md-writer#39]
I really like md-writer, which has lots of features I love, but there is one feature which I really want to have but is missing.

Headers start with # have perfect color highlight, however, headers marked with ====== or ------ don't. I personally prefer using equal or dash for level 1 header, since it is much clearer than # in the text form. Could you add this to the plugin?

**Comment by zhuochun** [comment]
Hi, great that you love this plugin!

For syntax highlight problem please submit to https://github.com/atom/language-gfm , the official package that handles syntax highlights for markdown.

**Comment by yantongl** [comment]
Thank you for the quick response. There is already a report on language-gfm project. I will follow up on them and close this issue.
