### ISSUE TITLE
"EACCES: permission denied, mkdir '/github'" when trying to add new post

### ISSUE THREAD

**Issue by christopherfujino** [zhuochun/md-writer#42]
In my working Jekyll blog directory, I tried to use the md-writer plugin to add a new post, but I got the error:

> EACCES: permission denied, mkdir '/github'

I'm not sure why it's trying to create a '/github' folder, nor where it's trying to create it. I'm starting atom as my user, and my user has read/write permissions in my Jekyll directory.

![screenshot](https://cloud.githubusercontent.com/assets/7856010/7081977/931831b2-dee7-11e4-95bd-c0bb1e8da2ca.png)

**Comment by zhuochun** [comment]
Hi, please change the settings accordingly, follow the guide at https://github.com/zhuochun/md-writer#setup

**Comment by christopherfujino** [comment]
Ahh, thanks for the quick response! I'll do that now.
