### ISSUE TITLE
Ordered List 快捷键不正确

### ISSUE THREAD

**Issue by shena1983** [zhuochun/md-writer#48]
每次更新后 Ordered List 的快捷键 都是 ctrl option 5

**Comment by zhuochun** [comment]
可以去 Settings -> Key Bindings -> 搜索 markdown-writer:toggle-ol 看看是哪儿绑定的？

**Comment by zhuochun** [comment]
安装最新的 v1.5.0 版本后，你可以自定义所有快捷键，参考 https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps
