### ISSUE TITLE
Package not loading due to deprecated APIs

### ISSUE THREAD

**Issue by shilman** [zhuochun/md-writer#49]
This is what I see after upgrading to `Atom 0.206.0` today:

![settings_-_atom](https://cloud.githubusercontent.com/assets/488689/7998358/e365df6a-0b75-11e5-8f1f-811cc092b48b.png)

**Comment by shilman** [comment]
Also "markdown-writer" / "md-writer" / etc are not showing up in package search results. Possibly related to this issue:

![settings_-__users_shilman_projects_shilman_blog_-_atom](https://cloud.githubusercontent.com/assets/488689/7998532/4d48c5e4-0b78-11e5-83a0-6d7a70d04bb7.png)

**Comment by zhuochun** [comment]
Emm, this is abnormal. I can find it on Atom packages and all deprecated APIs have been fixed long time ago.

Could you try to uninstall it from Atom and re-install using `apm install markdown-writer`. Remember to backup your settings.

**Comment by shilman** [comment]
Thanks for the quick response. This is what I get when I try to install from command line:

```
$ apm install markdown-writer
Installing markdown-writer to /Users/shilman/.atom/packages ✗
No available version compatible with the installed Atom version: 0.206.0
```

NOTE: this is the first time I've had a problem like this, after I installed Atom 0.206.0 this morning. Previously I had used markdown-writer without any problems for months.

**Comment by shilman** [comment]
@zhuochun are you running the most recent Atom release, 0.206.0?

**Comment by zhuochun** [comment]
Found the reason. Refer to http://blog.atom.io/2015/06/04/deprecated-apis-have-been-removed.html you can use `--include-deprecated-apis` for now. I will figure out what's goes wrong.

**Comment by shilman** [comment]
Tried using `--include-deprecated-apis` earlier, with no luck. I think that feature of Atom may not be working perfectly since it was just released?

Anyway, I am eagerly awaiting your fix. Let me know if I can help in any way... and thanks for creating such a useful tool!!!
