### ISSUE TITLE
Cmd-B conflicts with Atom built-in

### ISSUE THREAD

**Issue by bronson** [zhuochun/md-writer#51]
If you're going to override core Atom behavior, maybe make it opt-in?  It looks like Cmd-K and Cmd-Shift-O have this problem too.

Also, it seems like Cmd-H should hide the app...?  That's an OSX thing though, not an Atom thing.

**Comment by zhuochun** [comment]
You can unset the keymaps in `Atom -> Open your Key Map`:

```
'.platform-darwin atom-text-editor:not([mini])':
  'cmd-b': 'unset!'
  'cmd-h': 'unset!'
  'shift-cmd-O': 'unset!'
```

https://github.com/zhuochun/md-writer/wiki/Tips-and-FAQ#how-to-disable-default-key-mappings-eg-ctrl-alt-1-5

**Comment by bronson** [comment]
But Cmd-B is already useful in Markdown mode...  I would hate to remember which keybindings work or don't work depending on what type of file I'm editing.

Personally I've decided not to use md-writer.  The bindings just feel too invasive, and opting out only works until another binding is added.  Feel free to close this issue if you don't agree this is a problem.

**Comment by zhuochun** [comment]
In v1.5.0, I removed all mappings from package, you can specify all keymaps in your own keymap config files. Refer to https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps

**Comment by bronson** [comment]
Wow!  Looks great.

To be sure, I'm happy for md-writer to include a reasonable number of default keybindings...  I'd just like any bindings that override stock Atom to be opt-in.

Did you consider using more two-key combos, like your `cmd-j` or Atom's `cmd-k`?  For example, `ctrl-m ctrl-b` for bold, `ctrl-m ctrl-i` for italic, etc.  (though ctrl-m is used by Atom's go-to-matching-bracket, the merge-conflicts plugin already maps `ctrl-m d` so maybe it's fine to reuse it...  I haven't really thought this out yet).

Time to reinstall md-writer and map some keys.
