### ISSUE TITLE
Suggestion: Provide option to use `*` instead of `_` for italics

### ISSUE THREAD

**Issue by adunning** [zhuochun/md-writer#56]
While I can modify `config.coffee` to change the character used to denote italics, I would much prefer not to have to do this with every update; could this be a user-configurable choice?

Thanks for putting this package together; it's exactly what I was looking for.

**Comment by zhuochun** [comment]
It is configurable, open your user config, find `markdown-writer`, append:

```
'markdown-writer':
  ... any existing configs ...
  'textStyles':
    'italic': 'before': "*", 'after': "*"
```

**Comment by adunning** [comment]
Brilliant; sorry for missing that!
