### ISSUE TITLE
Apply formatting to current word when there is no selection

### ISSUE THREAD

**Issue by adunning** [zhuochun/md-writer#57]
Presently, if the cursor is placed in the middle of the word and one of the formatting commands is invoked, one will merely receive the appropriate characters on each side of the cursor. With the TextMate Markdown package (see https://github.com/textmate/markdown.tmbundle/tree/master/Commands), this action will result in the formatting being applied to the entirety of the current word (minus any punctuation), which is useful; would it be possible to implement this?

**Comment by zhuochun** [comment]
May I confirm the behavior when cursor is is inside a middle of the formatted text, and trigger the format command again? It will toggle format or insert format?

**Comment by adunning** [comment]
That's an interesting point: the TextMate 2 behaviour is to trigger it again: `**bolded**` becomes `****bolded****` if one moves the cursor back into the word and types <kbd>⌘</kbd> + <kbd>b</kbd> a second time. Removing it the second time would probably be more ideal, but I'm not sure whether that's feasible.

In my experience, the main undesirable aspect of the TextMate implementation is that, if the cursor is placed after a piece of punctuation at the end of a word and <kbd>⌘</kbd> + <kbd>i</kbd> (etc.) is invoked, one gets something like `example*,*`. (I would expect either `*example,*` or `*example*,`.)

**Comment by zhuochun** [comment]
@adunning i added this behaviour in the latest release. please try it out :dancers:

**Comment by adunning** [comment]
That's absolutely wonderful; thank you! The only oddity I'm seeing is that it's being invoked twice every time, appending additional characters to the word: placing the cursor in `word` and typing <kbd>⌘</kbd> + <kbd>b</kbd> results in `**word******`.

**Comment by zhuochun** [comment]
Em. I see the problem with `**word**_,` becomes `**word****_**,`. Might due to how Atom handles the boundary between word and non-word chars. I will check again :D

**Comment by adunning** [comment]
That's fairly minor; your implementation is even better than TextMate's otherwise. The problem I was having with the commands being run twice disappeared after I uninstalled the package and re-added it. Thanks again!
