### ISSUE TITLE
Enter No Longer Continues Lists in 1.7.1

### ISSUE THREAD

**Issue by FTWynn** [zhuochun/md-writer#58]
Confirmed in both Ubuntu on Atom 1.0.0 and OSX in 1.0.2. This is the only custom package installed aside from markdown-toc.

Enter doesn't seem to continue lists any longer.

Please let me know if I need to include any other information.

**Comment by zhuochun** [comment]
Emm. I didn't touch this feature in `v1.7`, and works fine in my environment. Can you try re-installing it? Thanks

**Comment by FTWynn** [comment]
Uninstall, reinstall, close Atom, open Atom... and resolved.

Man... is there no problem turning something off and on again won't fix?

I'm guessing there was some issue with upgrading the package and staying in the same editing session. Weird that it repro'd on both OS's, but that's a problem for another day.

Many thanks.
