### ISSUE TITLE
make it possible to use relative path of image

### ISSUE THREAD

**Issue by mangecoeur** [zhuochun/md-writer#60]
When inserting an image, I usually just want to paste the relative path compared to the current document, instead it automatically creates a blog-style path

**Comment by zhuochun** [comment]
I will check this when I am free in the weekend. Probably will add another config for this. Thanks.

**Comment by kakubei** [comment]
+1 for this please. I always use the local image name at the same level as the markdown file. But all my images get this path prepended: `/images/2015/11/` so I have to end up deleting it constantly. 

Thanks for the package!

**Comment by zhuochun** [comment]
In `v2.1.0`, please try go to settings -> markdown-writer -> enable relative image path

**Comment by kakubei** [comment]
This is really great, thanks. However, this update breaks the `autocomplete-plus` package's ability to select the suggested completion with any keyboard shortcut. 

Disabling the `markdown-writer` package enables `autocomplete-plus` to work again.

Any ideas how to fix this?

**Comment by zhuochun** [comment]
Hi please try restart atom and enable Markdown-Writer again to see things fixed.

Best regards,
Zhuochun

On Dec 8, 2015 2:12 AM, Alex <notifications@github.com> wrote:
This is really great, thanks. However, this update breaks the `autocomplete-plus` package's ability to select the suggested completion with any keyboard shortcut.

Disabling the `markdown-writer` package enables `autocomplete-plus` to work again.

Any ideas how to fix this?

---

**Comment by kakubei** [comment]
Thanks but restarting Atom does not fix the issue. The only way I was able to mitigate this is by disabling the markdown-writer Keybindings (see image). 
![keybindings](https://cloud.githubusercontent.com/assets/1465323/11715258/a44a2f52-9f40-11e5-86d9-c812151155c1.png)

This allows autocompletion to work properly, but I lose some of the automations provided by markdown-writer such as creating new numbers for a numbered list when pressing Return. 

Curiously, the other keyboard shortcuts, such as bold, italic, etc. Still work.

**Comment by zhuochun** [comment]
Problem identified. Should be fixed in next release. Thanks.

Except `enter` and `tab` shortcuts, other shortcuts are defined in your user mappings. `enter` and `tab` are defined in package. Hopefully will make them a configuration as `autocomplete-plus` does in future.

**Comment by zhuochun** [comment]
Ah, you can add this to your key map config instead:

```
"atom-workspace atom-text-editor:not([mini]):not(.autocomplete-active)[data-grammar~='gfm']":
  "enter": "markdown-writer:insert-new-line"
  "tab"  : "markdown-writer:indent-list-line"
```
