### ISSUE TITLE
Make path for customized _posts path

### ISSUE THREAD

**Issue by louisgv** [zhuochun/md-writer#62]
When publishing drafts using a custom _post path (e.g: _posts/{year}/{month}), md-writer throw an error saying the path was not found. I had to manually add the path in order to publish the draft.

It would be useful to have the plugin auto generate the path.

**Comment by zhuochun** [comment]
I think the path will be create automatically. Can you provides some steps to reproduce this error?

**Comment by zhuochun** [comment]
Create new draft does not handle `{year}` etc in path config.

**Comment by louisgv** [comment]
Reproducing errors:
* Change _posts path to: `_posts/{year}/{month}/`
* Make new draft
* Publish draft
![md-writer-bug](https://cloud.githubusercontent.com/assets/6723574/9166372/30fd3be6-3f07-11e5-8a0c-44a5187e56ba.png)
