### ISSUE TITLE
Changing default layout

### ISSUE THREAD

**Issue by Fastidious** [zhuochun/md-writer#72]
Right now when I create a new post, it is using the "post" layout as a default, which I do not use, my default layout is named (no pun intended) "default." I have looked in the settings for a place to set this to no avail. Is there a trick to change the new post layout to have a different one as a default?

Thanks!

**Comment by Fastidious** [comment]
Found the solution!

    "markdown-writer":
        [...]
        frontMatter: """
        ---
        layout: "default"
        title: "<title>"
        date: "<date>"
        ---
        """

**Comment by zhuochun** [comment]
Yes. The documentation is listed here: https://github.com/zhuochun/md-writer/wiki/Settings
