### ISSUE TITLE
Jekyll highlight tags are not rendering

### ISSUE THREAD

**Issue by mmoayyed** [zhuochun/md-writer#77]
Does the package support this syntax, as advertised on Jekyll?

```
{% highlight ruby %}
def foo
  puts 'foo'
end
{% endhighlight %}
```

**Comment by zhuochun** [comment]
The package add new commands to help writing in Jekyll. Syntax highlights are not part of the package for now.

**Comment by mmoayyed** [comment]
Well, if you could add them, that would be sweet. It's the one thing I miss :)
