### ISSUE TITLE
Auto-scroll preview pane

### ISSUE THREAD

**Issue by orschiro** [zhuochun/md-writer#79]
Dear all, 

I am very grateful for this package, thank you very much!

I have one question:

Is it technically possible to let the Markdown preview pane auto-scroll alongside the source code pane so that both always show the same content at the same cursor position?

Below a screencast to clarify my request further.

Thankfully,

Robert

[atom-markdown-preview-auto-scroll-2015-09-25_12.43.20.ogg | uploaded via ZenHub](https://files.zenhub.io/56058c59c4c3126521f449ea)

**Comment by zhuochun** [comment]
There is another package for this: https://atom.io/packages/markdown-scroll-sync

**Comment by orschiro** [comment]
Dear @zhuochun,

Thank you very much for the references!

The package is working perfectly.

Warmly,

Robert
