### ISSUE TITLE
markdown-writer:insert-new-line is broken

### ISSUE THREAD

**Issue by crucialfelix** [zhuochun/md-writer#84]
With the new update (2.0.1) when I hit enter there is no newline created. I have to hold option-enter

I can see in Key Binding Resolver that markdown-writer:insert-new-line is matching, but there is no newline created.

![screen shot 2015-09-28 at 12 53 54](https://cloud.githubusercontent.com/assets/218738/10133727/05495dc2-65e0-11e5-8c99-97affc254c3c.png)

**Comment by zhuochun** [comment]
Could you provide more details, the file type you are editing, any errors show up in the console?

**Comment by zhuochun** [comment]
If you just update the plugin, could try to restart Atom.

**Comment by crucialfelix** [comment]
Restarting Atom did work. 

I'm not sure what went wrong but there, but I wouldn't worry about it.

thanks !
