### ISSUE TITLE
Site engine (Pelican Blog)

### ISSUE THREAD

**Issue by intranets-talk** [zhuochun/md-writer#87]
This is not an issue, it is a request for adding Pelican blogging at the Site Engine in settings, if possible. 

When you start a new post (in Markdown),  the following example represents a Pelican format for the page top:
```
Title: Some post
Date: 2014-12-14 02:53
Author: J Doe
Category: Tutorials
Tags: backup, ftp, mysql
Slug: some-post
Status: published
```
I have currently set the engine to General, and adjust this manually, it would be nice to have a choice in settings for this.

Thanks,
Gabriel.

**Comment by zhuochun** [comment]
You can edit the front matter text in Atom config or project config. Refer to https://github.com/zhuochun/md-writer/wiki/Settings-for-individual-projects

I am not familiar with Pelican. Would you help submit a PR?

**Comment by intranets-talk** [comment]
Thanks zhuochun - I'll have a close look at the project config file and will be looking into submitting a PR.
