### ISSUE TITLE
Is it possible to use the "New Post" feature with several projects?

### ISSUE THREAD

**Issue by state-man** [zhuochun/md-writer#88]
Currently the only way I've found to use this feature is to specify the project path in the settings.

I have several blogs, so help is appreciated!

**Comment by zhuochun** [comment]
Currently, you can add project specific config, then open the project, `new post` will pick the project config. Globally, `new post` don't support select projects yet.

**Comment by zhuochun** [comment]
You can use https://atom.io/packages/project-manager to switching projects.

As a self note, probably can integrate its service API to provide projects support.
