### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by fusion809** [zhuochun/md-writer#91]
Hi,

I would like to bold text with the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>B</kbd> and this is my default `~/.atom/keymap.cson` file:

```cson
# Default Keymaps for Markdown Writer
# https://atom.io/packages/markdown-writer
#
# Wiki: https://github.com/zhuochun/md-writer/wiki/Settings-for-Keymaps
#
".platform-linux atom-text-editor[data-grammar~='gfm']":
  "shift-ctrl-K": "markdown-writer:insert-link"
  "shift-ctrl-I": "markdown-writer:insert-image"
  "ctrl-i":       "markdown-writer:toggle-italic-text"
  "ctrl-b":       "markdown-writer:toggle-bold-text"
  "ctrl-'":       "markdown-writer:toggle-code-text"
  "ctrl-h":       "markdown-writer:toggle-strikethrough-text"
  "ctrl-1":       "markdown-writer:toggle-h1"
  "ctrl-2":       "markdown-writer:toggle-h2"
  "ctrl-3":       "markdown-writer:toggle-h3"
  "ctrl-4":       "markdown-writer:toggle-h4"
  "ctrl-5":       "markdown-writer:toggle-h5"
```

yet whenever I press <kbd>Ctrl</kbd>+<kbd>B</kbd> some opened file search window pops up, that is shown below:

![File search popup](http://imgur.com/wf1sTT2l.png)

now if you're wondering whether one of my plugins is doing this, well I doubt it as these are the only plugins/themes I've installed manually (that is, those that didn't come bundled with Atom 1.2.4):

```sh
├── git-plus@5.6.6
├── jekyll@1.0.0
├── jekyll-snippets@0.3.2
├── language-gentoo@0.8.0
├── language-markdown@0.5.1
├── markdown-writer@2.0.1
├── minimal-syntax-dark@0.1.7
├── pigments@0.19.1
└── wordcount@2.4.1
```

If relevant my OS is Sabayon Linux and my Atom version is, as previously mentioned 1.2.4. 

Thanks for your time,
Brenton

**Comment by zhuochun** [comment]
Can you try the lowercase `Ctrl + b`? In settings -> keybindings, can check the conflicting bindings.

**Comment by kswedberg** [comment]
I'm having the same issue with keybindings not working, but only when I've set the grammar to `Markdown` (using the language-markdown package, which uses `text.md` grammar). When I set the grammar to `GitHub Markdown`, the kdy bindings work as expected.

**Comment by kswedberg** [comment]
@zhuochun is there any way you could include `text.md` to the list of supported grammars at https://github.com/zhuochun/md-writer/blob/master/lib/config.coffee#L131-L135 ?

Or, could you perhaps expose the grammars as a setting the way markdown-preview-plus does? (https://github.com/Galadirith/markdown-preview-plus/blob/master/lib/main.coffee#L34-L42)

Thanks!

**Comment by kswedberg** [comment]
Never mind (and sorry for the multiple comments). I just updated my config.cson file to include the following:

```
"markdown-writer":
    fileExtension: ".md"
    grammars: [
      "text.md"
      "source.gfm"
      "source.litcoffee"
      "text.plain"
      "text.plain.null-grammar"
    ]```

And it appears to be working great now. @fusion809 : maybe the same will do the trick for you, as well?

**Comment by zhuochun** [comment]
:+1: All markdown-writer settings in `config.coffee` can be overwritten by manually editing your `config.cson`.

Because there are too many configs, so some are not shown in the plugin settings page.

**Comment by netsi1964** [comment]
@fusion809 I had same issue (on windows), however I went to menu point: `Packages > Markdown Writer > Configurations > Create Default Keymaps` which generated a file `keymap.cson`. I saved it and voila, I could use `ctrl+b` (and the other) keyboard short cuts.

**Comment by Orebeer** [comment]
netsi I'm jealous that you have such config options in Windows. Does anyone have a solution for this on Mac? If not, it would be great to have a reference file on how to manually config the general keybindings to the keymap. Thanks!

**Comment by netsi1964** [comment]
@Orebeer This is not a "windows-thing". It is an a feature of Markdown Writer package. Something which  a package can choose to implement, and MW did :-) So no matter if you are running your Atom on OS X, Windows (or other platforms) you can do as I wrote. So go ahead and hover over Packages menu item and then hover over "Markdown Writer"... all the way to "Create Default Keymaps" and you can also create your own shortcut.

**Comment by chrisduong** [comment]
Hi, 

I did try the same way. 

Edit my config.cson:
```
  "markdown-writer":
    fileExtension: ".md"
    grammars: [
      "text.md"
      "source.gfm"
      "source.litcoffee"
      "text.plain"
      "text.plain.null-grammar"
    ]
```

Define my keymap.cson:
```
# "atom-text-editor:not([mini])[data-grammar~='gfm']":
# "atom-text-editor:not([mini])[data-grammar~='markdown']":
"atom-text-editor:not([mini])":
  "shift-cmd-K": "markdown-writer:insert-link"
  "shift-cmd-I": "markdown-writer:insert-image"
  "cmd-i":       "markdown-writer:toggle-italic-text"
  "cmd-b":       "markdown-writer:toggle-bold-text"
```

If I include **data-grammar**, it never works.

I'm using the Atom version **1.6.0**.

**Comment by smellflower** [comment]
![image](https://cloud.githubusercontent.com/assets/1149610/22674790/dbdaa3c2-ed1c-11e6-8488-9b75f423a3ad.png)
