### ISSUE TITLE
Markdown-Writer keybinding take precedence over confirm of autocompletion suggestions

### ISSUE THREAD

**Issue by hwroitzsch** [zhuochun/md-writer#98]
I described the bug here: https://discuss.atom.io/t/autocomplete-plus-key-not-working/23613

**Comment by zhuochun** [comment]
Yep. Follow the answer in discussion:

You can go into the settings for the markdown-writer package, disable the bundled keybindings and then bind your own copies of them.

```
"atom-workspace atom-text-editor:not([mini]):not(.autocomplete-active)[data-grammar~='gfm']":
  "enter": "markdown-writer:insert-new-line"
  "tab"  : "markdown-writer:indent-list-line"
```

Issue at https://github.com/zhuochun/md-writer/issues/60 might help

**Comment by hwroitzsch** [comment]
Thanks, that solved the problem and taught me something about the key binding "language" : ) and key bindings of packages in general.
