### ISSUE TITLE
Create new post --- the post name cannot recognize Chinese

### ISSUE THREAD

**Issue by wens07** [zhuochun/md-writer#99]
when use the shortcut key to create a new post, the name in chinese cannot recognize

**Comment by wens07** [comment]
i am using Atom 1.3.1,  md-writer 2.1, mac os x 10.10.5;  the new created post in blog directory cannot have chinese.

**Comment by zhuochun** [comment]
You mean the post name is Chinese? or the directory itself contains folder with Chinese?

**Comment by wens07** [comment]
in my case, it's the post name int chinese

**Comment by wens07** [comment]
the setting of new post is: `sitePostsDir: "source/_posts/{year}/{month}/"`
                                          `newPostFileName: "{title}-{year}-{month}-{day}{extension}"`

**Comment by Mez0** [comment]
Having the same problem.  
When creating new post, the file name will be blank when the post name is Chinese.
